"""Pydantic schemas — the single source of truth for every shape crossing
the API boundary.

These intentionally mirror two upstream contracts so integration needs no
translation layer:

1. device-hub's `StandardData.to_dict()` output -> IncomingData (POST /data)
2. The AI-core spec's memory format -> Memory (GET/POST /memory)
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field, field_validator

from app.config import SUPPORTED_SOURCES


# ---------------------------------------------------------------------------
# Incoming personal data (POST /data) — matches device-hub StandardData
# ---------------------------------------------------------------------------


class IncomingData(BaseModel):
    """One authorized-or-not data item, in the shared data contract shape.

    {
      "source": "notes | calendar | health | device | messages",
      "timestamp": "ISO-8601",
      "permission": true,
      "data": {}
    }
    """

    source: str
    timestamp: datetime
    permission: bool
    data: dict[str, Any] = Field(default_factory=dict)

    @field_validator("source")
    @classmethod
    def source_must_be_supported(cls, value: str) -> str:
        if value not in SUPPORTED_SOURCES:
            supported = ", ".join(sorted(SUPPORTED_SOURCES))
            raise ValueError(f"source must be one of: {supported}")
        return value


class DataIngestResult(BaseModel):
    """What we tell the caller happened to their POST /data submission."""

    stored: bool
    reason: str
    source: str
    id: Optional[str] = None


# ---------------------------------------------------------------------------
# Memory — matches the AI-core spec's memory format exactly
# ---------------------------------------------------------------------------


class MemoryBase(BaseModel):
    content: str
    source: str
    importance: float = 0.5

    @field_validator("source")
    @classmethod
    def source_must_be_supported(cls, value: str) -> str:
        if value not in SUPPORTED_SOURCES:
            supported = ", ".join(sorted(SUPPORTED_SOURCES))
            raise ValueError(f"source must be one of: {supported}")
        return value

    @field_validator("importance")
    @classmethod
    def importance_in_range(cls, value: float) -> float:
        if not 0.0 <= value <= 1.0:
            raise ValueError("importance must be between 0.0 and 1.0")
        return value


class MemoryCreate(MemoryBase):
    """Body for POST /memory.

    Deliberately has no id/timestamp fields: both are generated by the
    backend so callers can never spoof a memory's creation time or collide
    on an id.
    """


class Memory(MemoryBase):
    """A stored memory, as returned by GET /memory."""

    id: str
    timestamp: datetime


class MemoryDeleteResult(BaseModel):
    """Response for DELETE /memory/{id}."""

    deleted: bool
    id: str


class MemoryClearResult(BaseModel):
    """Response for DELETE /memory (clears every stored memory)."""

    deleted_count: int


# ---------------------------------------------------------------------------
# Permissions
# ---------------------------------------------------------------------------


class PermissionUpdate(BaseModel):
    source: str
    permission: bool

    @field_validator("source")
    @classmethod
    def source_must_be_supported(cls, value: str) -> str:
        if value not in SUPPORTED_SOURCES:
            supported = ", ".join(sorted(SUPPORTED_SOURCES))
            raise ValueError(f"source must be one of: {supported}")
        return value


class PermissionState(BaseModel):
    source: str
    permission: bool


class PermissionToggle(BaseModel):
    enabled: bool


class PermissionUpdateResponse(BaseModel):
    source: str
    enabled: bool


# ---------------------------------------------------------------------------
# Chat
# ---------------------------------------------------------------------------


class ChatRequest(BaseModel):
    message: str

    @field_validator("message")
    @classmethod
    def message_must_not_be_empty(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("message must not be empty")
        return value


class UsedContext(BaseModel):
    label: str
    sourceId: str


class ChatResponse(BaseModel):
    response: str
    used_context: list[UsedContext] = Field(default_factory=list)
    memory_ids: list[str] = Field(default_factory=list)


class ChatHistoryMessage(BaseModel):
    id: str
    role: Literal["user", "assistant"]
    content: str
    timestamp: datetime


class ChatHistoryClearResult(BaseModel):
    deleted_count: int


# ---------------------------------------------------------------------------
# Documents (Phase 4, schema defined now so models are all in one place)
# ---------------------------------------------------------------------------


class DocumentUploadResult(BaseModel):
    document_id: str
    filename: str
    chunk_count: int
    status: str


class HealthResponse(BaseModel):
    status: str
    service: str = "lumi-backend"
